### ISSUE TITLE
Review Order Page

### ISSUE THREAD

**Issue by JTY009** [RytisJ/qa_play_project#161] opened 2016-07-22 09:22 UTC
I suggest adding this page to review the payment of the order that has been confirmed and the items listed in that order.

**Comment by Smudgey** [comment] 2016-07-22 14:13
Duplicate of #121

**Comment by Smudgey** [comment] 2016-07-22 14:15
This is actually for customer satisfaction and not for product rating

**Comment by Smudgey** [comment] 2016-07-22 14:15
Where do we want customer satisfaction to go and what sort of information are we seeking?

**Comment by RytisJ** [comment] 2016-07-25 11:59
sorted in #184

**Closed by RytisJ** 2016-07-25 11:59 UTC
